import { describe, expect, it } from 'vitest';
import { generateKotlin, type OpenApiDocument } from './kotlin.js';

const PACKAGE = 'net.develivarr.auralis.generated.api';

function withHealth(properties: Record<string, object>, required: string[] = []): OpenApiDocument {
  return {
    components: {
      schemas: { HealthResponse: { type: 'object', properties, required } },
    },
  };
}

describe('the Kotlin generator', () => {
  it('maps a required, an optional and a nullable property', () => {
    const kotlin = generateKotlin(
      withHealth(
        {
          name: { type: 'string' },
          count: { type: 'integer' },
          note: { type: ['string', 'null'] },
          size: { type: 'integer', format: 'int64' },
          tags: { type: 'array', items: { type: 'string' } },
        },
        ['name', 'note', 'size', 'tags'],
      ),
      PACKAGE,
    );
    expect(kotlin).toContain('    val name: String,\n');
    expect(kotlin).toContain('    val count: Int? = null,\n');
    expect(kotlin).toContain('    val note: String?,\n');
    expect(kotlin).toContain('    val size: Long,\n');
    expect(kotlin).toContain('    val tags: List<String>,\n');
  });

  it('names an inline enum after its object and property', () => {
    const kotlin = generateKotlin(
      withHealth({ status: { type: 'string', enum: ['ok'] } }, ['status']),
      PACKAGE,
    );
    expect(kotlin).toBe(
      [
        '// Generated by `pnpm gen` from schema/src. Do not edit.',
        'package net.develivarr.auralis.generated.api',
        '',
        'import kotlinx.serialization.SerialName',
        'import kotlinx.serialization.Serializable',
        '',
        '@Serializable',
        'data class HealthResponse(',
        '    val status: HealthResponseStatus,',
        ')',
        '',
        '@Serializable',
        'enum class HealthResponseStatus {',
        '    @SerialName("ok")',
        '    OK,',
        '}',
        '',
      ].join('\n'),
    );
  });

  it('refers to another component by name', () => {
    const kotlin = generateKotlin(
      {
        components: {
          schemas: {
            Item: {
              type: 'object',
              properties: { kind: { $ref: '#/components/schemas/Kind' } },
              required: ['kind'],
            },
            Kind: { type: 'string', enum: ['book', 'audioBook'] },
          },
        },
      },
      PACKAGE,
    );
    expect(kotlin).toContain('    val kind: Kind,\n');
    expect(kotlin).toContain('    @SerialName("book")\n    BOOK,\n');
    expect(kotlin).toContain('    @SerialName("audioBook")\n    AUDIO_BOOK,\n');
  });

  it('refuses a shape it cannot map', () => {
    const shapes: Record<string, object>[] = [
      { choice: { oneOf: [{ type: 'string' }, { type: 'integer' }] } },
      { class: { type: 'string' } },
      { nested: { type: 'object', properties: { a: { type: 'string' } } } },
      { other: { $ref: '#/components/schemas/Missing' } },
    ];
    for (const properties of shapes) {
      expect(() => generateKotlin(withHealth(properties), PACKAGE)).toThrow(/HealthResponse\./);
    }
  });
});
