import openapiTS, { astToString } from 'openapi-typescript';

/** `paths` and `components` types for openapi-fetch, from the OpenAPI document. */
export async function generateTypeScript(doc: object): Promise<string> {
  const ast = await openapiTS(doc as Parameters<typeof openapiTS>[0]);
  return `/** Generated by \`pnpm gen\` from schema/src. Do not edit. */\n\n${astToString(ast)}`;
}
