import { describe, expect, it } from 'vitest';
import { generateKotlinNotActions, NOT_ACTIONS } from './actions.js';

describe('the not-actions list', () => {
  const kotlin = generateKotlinNotActions().get('NotActions.kt')!;

  it('[M0.states/b] gives Android every pair the web reads, generated', () => {
    expect(kotlin.split('\n')[0]).toBe('// Generated by pnpm gen from design/sonora. Do not edit.');
    const pairs = [...kotlin.matchAll(/^\s+"(\w+)" to "(\w+)",$/gm)].map(([, c, p]) => `${c}.${p}`);
    expect(pairs).toEqual(NOT_ACTIONS.map((n) => `${n.component}.${n.prop}`));
  });

  it('[M0.states/b] lists the queue handlers that NowPlaying takes flat on Android as not actions', () => {
    expect(kotlin).toContain('"NowPlaying" to "onEditingChange",');
    expect(kotlin).toContain('"NowPlaying" to "onReorder",');
  });
});
