import { describe, expect, it } from 'vitest';
import { generateKotlin } from './kotlin.js';
import { modelOf, oneComponent } from './test-sonora.js';

const PKG = 'net.example.ui';
const kotlinOf = (sources: Record<string, string>) => generateKotlin(modelOf(sources), PKG);
/** The one property line `member` becomes in XProps. */
function lineOf(member: string): string {
  const file = kotlinOf(oneComponent(member)).get('XProps.kt')!;
  const lines = file.split('\n');
  const start = lines.indexOf('data class XProps(');
  return lines[start + 1]!.trim();
}

describe('Kotlin props classes', () => {
  it.each<[string, string]>([
    ['a?: string;', 'val a: String? = null,'],
    ['a: string;', 'val a: String,'],
    ['a: boolean;', 'val a: Boolean,'],
    ['a?: number;', 'val a: Float? = null,'],
    ['a: number | null;', 'val a: Float?,'],
    ["a?: 'now' | string;", 'val a: String? = null,'],
    ['a: string | number;', 'val a: Any,'],
    ['a?: string[];', 'val a: List<String>? = null,'],
    ['a: Array<string | number>;', 'val a: List<Any>,'],
    ['a?: Record<string, string>;', 'val a: Map<String, String>? = null,'],
    ['a: ReactNode;', 'val a: (@Composable () -> Unit)?,'],
    ['a?: ReactNode;', 'val a: (@Composable () -> Unit)? = null,'],
    [
      'a?: ((n: number) => ReactNode) | ReactNode;',
      'val a: (@Composable (Float) -> Unit)? = null,',
    ],
    ['a?: () => void;', 'val a: (() -> Unit)? = null,'],
    ['a: () => void;', 'val a: () -> Unit,'],
    ['a?: (from: number, to: number) => void;', 'val a: ((Float, Float) -> Unit)? = null,'],
    ['a?: (key: string) => string | number;', 'val a: ((String) -> Any)? = null,'],
    ['a?: (origin: DOMRect | null) => void;', 'val a: ((Rect?) -> Unit)? = null,'],
    ['onA?: (e?: any) => void;', 'val onA: (() -> Unit)? = null,'],
    ['onA?: (e: MouseEvent) => void;', 'val onA: (() -> Unit)? = null,'],
    ['a: JSX.Element;', 'val a: @Composable () -> Unit,'],
    ["a?: 'x' | 'y';", 'val a: XA? = null,'],
    ['a?: { x: number };', 'val a: XA? = null,'],
    ['a?: boolean | number;', 'val a: XA? = null,'],
  ])('[M0.uikit/a] %s becomes %s', (member, line) => {
    expect(lineOf(member)).toBe(line);
  });

  it('[M0.uikit/a] writes one file per component: the props class, then its own enums, classes and KDoc', () => {
    const files = kotlinOf({
      'layout/Scroller.d.ts': [
        "import { ReactNode, CSSProperties } from 'react';",
        '',
        '/**',
        ' * A scroller.',
        ' *',
        ' * Keeps a `/*` opener.',
        ' */',
        'export interface ScrollerProps {',
        '  children?: ReactNode;',
        '  /** Which way. */',
        "  axis?: 'y' | 'x';",
        '  style?: CSSProperties;',
        '  edgeFade?: boolean | number;',
        '  origin?: { x: number; y: number } | null;',
        '  onPick?: (origin: DOMRect | null) => void;',
        '}',
        'export declare function Scroller(props: ScrollerProps): JSX.Element;',
        '',
      ].join('\n'),
    });
    expect([...files.keys()]).toEqual(['ScrollerProps.kt']);
    expect(files.get('ScrollerProps.kt')).toBe(
      [
        '// Generated by pnpm gen from design/sonora. Do not edit.',
        'package net.example.ui',
        '',
        'import androidx.compose.runtime.Composable',
        'import androidx.compose.ui.geometry.Rect',
        '',
        '/**',
        ' * A scroller.',
        ' *',
        ' * Keeps a `/&#42;` opener.',
        ' *',
        ' * Web only: style.',
        ' */',
        'data class ScrollerProps(',
        '    val children: (@Composable () -> Unit)? = null,',
        '    /** Which way. */',
        '    val axis: ScrollerAxis? = null,',
        '    val edgeFade: ScrollerEdgeFade? = null,',
        '    val origin: ScrollerOrigin? = null,',
        '    val onPick: ((Rect?) -> Unit)? = null,',
        ')',
        '',
        'enum class ScrollerAxis(val value: String) {',
        '    Y("y"),',
        '    X("x"),',
        '}',
        '',
        'sealed interface ScrollerEdgeFade {',
        '    @JvmInline',
        '    value class OfBoolean(val value: Boolean) : ScrollerEdgeFade',
        '',
        '    @JvmInline',
        '    value class OfFloat(val value: Float) : ScrollerEdgeFade',
        '}',
        '',
        'data class ScrollerOrigin(',
        '    val x: Float,',
        '    val y: Float,',
        ')',
        '',
      ].join('\n'),
    );
  });

  it('[M0.uikit/a] writes the shared enums to SonoraEnums.kt and a multi-line prop doc as a block', () => {
    const files = kotlinOf({
      'core/A.d.ts':
        "export interface AProps {\n  /**\n   * One.\n   * Two.\n   */\n  platform?: 'desktop' | 'mobile';\n}\n",
      'core/B.d.ts': "export interface BProps { platform: 'mobile' | 'desktop'; }\n",
    });
    expect(files.get('AProps.kt')).toBe(
      [
        '// Generated by pnpm gen from design/sonora. Do not edit.',
        'package net.example.ui',
        '',
        'data class AProps(',
        '    /**',
        '     * One.',
        '     * Two.',
        '     */',
        '    val platform: Platform? = null,',
        ')',
        '',
      ].join('\n'),
    );
    expect(files.get('SonoraEnums.kt')).toBe(
      [
        '// Generated by pnpm gen from design/sonora. Do not edit.',
        'package net.example.ui',
        '',
        'enum class Platform(val value: String) {',
        '    DESKTOP("desktop"),',
        '    MOBILE("mobile"),',
        '}',
        '',
      ].join('\n'),
    );
  });

  it('[M0.uikit/a] a generic interface is a generic data class', () => {
    const files = kotlinOf({
      'layout/L.d.ts':
        "import { ReactNode } from 'react';\nexport interface LRow<T> { item: T; }\nexport interface LProps<T = any> { items?: T[]; renderRow: (row: LRow<T>) => ReactNode; }\n",
    });
    expect(files.get('LProps.kt')).toBe(
      [
        '// Generated by pnpm gen from design/sonora. Do not edit.',
        'package net.example.ui',
        '',
        'import androidx.compose.runtime.Composable',
        '',
        'data class LRow<T>(',
        '    val item: T,',
        ')',
        '',
        'data class LProps<T>(',
        '    val items: List<T>? = null,',
        '    val renderRow: @Composable (LRow<T>) -> Unit,',
        ')',
        '',
      ].join('\n'),
    );
  });

  it('[M0.uikit/a] refuses a prop name Kotlin cannot use', () => {
    expect(() => kotlinOf(oneComponent('  when?: string;'))).toThrow(
      'X.when: not a Kotlin property name',
    );
  });
});
