import { fileURLToPath } from 'node:url';

export const REPO_ROOT = fileURLToPath(new URL('../..', import.meta.url));

/** Where `pnpm gen` reads Sonora and the canvas, and the folders it owns, relative to the repo root. */
export const SONORA_DIR = 'design/sonora';
export const APP_DIR = 'design/app';

export const OUTPUTS = {
  web: 'web/src/generated/ui',
  kotlin: 'android/app/src/main/java/net/develivarr/auralis/generated/ui',
  webNav: 'web/src/generated/nav',
  webPages: 'web/src/generated/pages',
  webTokens: 'web/src/generated/tokens',
  kotlinTheme: 'android/sonora/src/main/java/net/develivarr/auralis/generated/theme',
} as const;

export const KOTLIN_PACKAGE = 'net.develivarr.auralis.generated.ui';
export const KOTLIN_THEME_PACKAGE = 'net.develivarr.auralis.generated.theme';

/** The first line of every generated file. */
export const GENERATED_NOTE = 'Generated by pnpm gen from design/sonora. Do not edit.';
export const APP_NOTE = 'Generated by pnpm gen from design/app. Do not edit.';
