/** Where `pnpm gen` reads Sonora and the two folders it owns, relative to the repo root. */
export const SONORA_DIR = 'design/sonora';

export const OUTPUTS = {
  web: 'web/src/generated/ui',
  kotlin: 'android/app/src/main/java/net/develivarr/auralis/generated/ui',
} as const;

export const KOTLIN_PACKAGE = 'net.develivarr.auralis.generated.ui';

/** The first line of every generated file. */
export const GENERATED_NOTE = 'Generated by pnpm gen from design/sonora. Do not edit.';
